name: patient_tracking_app
description: "A new Flutter project for patient interaction"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  location: ^5.0.3
  hooks_riverpod: ^2.5.1
  google_maps_flutter: ^2.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


